name: hancod_theme
description: "Theme package for Hancod"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  form_builder_extra_fields: ^11.0.0
  form_builder_validators: ^11.0.0
  multi_dropdown: ^3.0.1
  phone_form_field: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/fonts/DMSans

  fonts:
  - family: DMSans
    fonts:
      - asset: assets/fonts/DMSans/DMSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/DMSans/DMSans-Thinitalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/DMSans/DMSans-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/DMSans/DMSans-ExtraLightitalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/DMSans/DMSans-Light.ttf
        weight: 300
      - asset: assets/fonts/DMSans/DMSans-Lightitalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/DMSans/DMSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/DMSans/DMSans-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/DMSans/DMSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/DMSans/DMSans-Mediumitalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/DMSans/DMSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/DMSans/DMSans-SemiBolditalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/DMSans/DMSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/DMSans/DMSans-Bolditalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/DMSans/DMSans-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/DMSans/DMSans-ExtraBolditalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/DMSans/DMSans-Black.ttf
        weight: 900
      - asset: assets/fonts/DMSans/DMSans-Blackitalic.ttf
        weight: 900
        style: italic
