name: hancod_theme
description: "Theme package for Hancod"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  form_builder_extra_fields: ^11.0.0
  form_builder_validators: ^11.0.0
  multi_dropdown: ^3.0.1
  phone_form_field: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/fonts/

  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato/Lato-Thin.ttf
        weight: 100
      - asset: assets/fonts/Lato/Lato-Thinitalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Lato/Lato-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Lato/Lato-ExtraLightitalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Lato/Lato-Light.ttf
        weight: 300
      - asset: assets/fonts/Lato/Lato-Lightitalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Lato/Lato-Regular.ttf
        weight: 400
      - asset: assets/fonts/Lato/Lato-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Lato/Lato-Medium.ttf
        weight: 500
      - asset: assets/fonts/Lato/Lato-Mediumitalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Lato/Lato-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Lato/Lato-SemiBolditalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Lato/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/Lato/Lato-Bolditalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Lato/Lato-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Lato/Lato-ExtraBolditalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Lato/Lato-Black.ttf
        weight: 900
      - asset: assets/fonts/Lato/Lato-Blackitalic.ttf
        weight: 900
        style: italic
